[package]
name = "geodynamix"
version = "0.16.0"
edition = "2021"

[package.metadata.vcpkg]
dependencies = [
    "gdal[core,netcdf,zstd,expat]",
    "hdf5[core,zlib]",
    "netcdf-c[core,netcdf-4,hdf5]",
    "tiff[core,lzma,zstd]",
] # needed to run the geo tests
git = "https://github.com/microsoft/vcpkg"
overlay-triplets-path = "infra-rs/vcpkg-overlay/triplets"
rev = "ce613c4"

[package.metadata.vcpkg.target]
x86_64-pc-windows-msvc = { triplet = "x64-windows-static-release" }
x86_64-apple-darwin = { triplet = "x64-osx-release" }
aarch64-apple-darwin = { triplet = "arm64-osx-release" }
x86_64-unknown-linux-gnu = { triplet = "x64-linux-release" }


[workspace]
members = ["infra-rs/crates/geo", "infra-rs/crates/inf"]

[lib]
name = "geodynamix"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.25", features = ["extension-module"] }
pyo3-log = "0.12"
numpy = "0.25"
inf = { path = "infra-rs/crates/inf" }
geo = { path = "infra-rs/crates/geo", features = ["gdal", "python"] }
num = "0.4"

[features]
default = []
static_build = ["geo/gdal-static"]

[patch.crates-io]
# more recent geozero to avoid multiple gdal copies
geozero = { git = "https://github.com/georust/geozero.git", rev = "e52422b54ab469ce8de6e33f859d4321be63d657" }
crs-definitions = { git = "https://github.com/dirkvdb/crs-definitions.git", rev = "9d01fb7993537a3ba632bf60899b884434a1d453" }
proj4wkt = { git = "https://github.com/3liz/proj4wkt-rs.git", rev = "942030821e6c0201d1ff899bcfc981799566b324" }
tiff = { git = "https://github.com/dirkvdb/image-tiff.git", rev = "47811747dda727073d6d48be918ce5831e124174" }
