[package]
name = "geodynamix"
version = "0.16.0"
edition = "2021"

[workspace]
members = ["infra-rs/crates/geo", "infra-rs/crates/inf"]

[lib]
name = "geodynamix"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.23", features = ["extension-module"] }
pyo3-log = "0.12"
numpy = "0.23"
inf = { path = "infra-rs/crates/inf" }
geo = { path = "infra-rs/crates/geo", features = ["gdal", "python"] }

[features]
default = []
static_build = ["geo/gdal-static"]

[package.metadata.vcpkg]
git = "https://github.com/microsoft/vcpkg"
rev = "10b7a17"
dependencies = [
    "gdal[core,netcdf,sqlite3]",
    "netcdf-c[core,netcdf-4,hdf5]",
] # needed to run the geo tests

[patch.crates-io]
# more recent geozero to avoid multiple gdal copies
geozero = { git = "https://github.com/georust/geozero.git", rev = "66583383b995925c3eef0a01cd5781b1d59e8209" }
