[build-system]
requires      = ["maturin>=1.8,<2.0"]
build-backend = "maturin"

[project]
name = "geodynamix"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
    "Programming Language :: Rust",
]
dynamic = ["version"]

[tool.maturin]
module-name   = "geodynamix"
python-source = "python"
profile       = "release"
features      = ["static_build"]
bindings      = "pyo3"
manifest-path = "Cargo.toml"
strip         = true
data          = "python/geodynamix.data"

[tool.pixi.project]
channels  = ["conda-forge"]
platforms = ["linux-64", "osx-64", "osx-arm64", "win-64"]

[tool.pixi.tasks]
test = "pytest -s tests/*.py"

[tool.pixi.build-dependencies]
maturin = ">=1.8.1,<2"
pytest  = ">=8.3.4,<9"
pip     = ">=25.0,<26"

[tool.pixi.dependencies]
numpy = ">=2.2.2,<3"
