VCPKG_DEFAULT_TRIPLET := if os_family() == "windows" {
    "x64-windows-static"
} else if os() == "macos" {
    if arch() == "aarch64" {
        "arm64-osx"
    } else { "x64-osx" }
} else {
    "x64-linux"
}

cmake_preset := if os_family() == "windows" {
    "windows"
} else if os() == "macos" {
    if arch() == "aarch64" {
        "mac-arm"
    } else { "mac-intel" }
} else {
    "linux"
}

export VCPKG_ROOT := env('VCPKG_ROOT', "../../vcpkg")

bootstrap:
    '{{VCPKG_ROOT}}/vcpkg' install --allow-unsupported --triplet {{VCPKG_DEFAULT_TRIPLET}}

configure: bootstrap
    cmake --preset {{cmake_preset}}

build: configure
    cmake --build ./build

test: build
    ctest --test-dir ./build