#!/bin/bash
set -e

mkdir ${SRC_DIR}/build

cd ${SRC_DIR}/build
# unset the SYSCONFIGDATA_NAME otherwise pybind11 python module extension detection fails
unset _CONDA_PYTHON_SYSCONFIGDATA_NAME
cmake \
    -G Ninja \
    ${CMAKE_ARGS} \
    -DPACKAGE_VERSION_COMMITHASH=${GIT_FULL_HASH} \
    -DCMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH} \
    -DCMAKE_FIND_ROOT_PATH:PATH="${PREFIX};${BUILD_PREFIX}/x86_64-conda-linux-gnu/sysroot" \
    -DCMAKE_MODULE_PATH="${RECIPE_DIR}/cmake" \
    -DGDX_DISABLE_OPENMP=OFF \
    -DGDX_ENABLE_TOOLS=OFF \
    -DGDX_ENABLE_TESTS=OFF \
    -DGDX_ENABLE_TEST_UTILS=OFF \
    -DGDX_PYTHON_BINDINGS=ON \
    -DINFRA_ENABLE_TESTS=OFF \
    -DINFRA_EMBED_GDAL_DATA=OFF \
    -DCMAKE_BUILD_TYPE=Release \
    -DGDX_INSTALL_DEVELOPMENT_FILES=OFF \
    -DGDX_ENABLE_OPENMP=OFF \
    -DGDX_ENABLE_SIMD=OFF \
    -DGDX_ENABLE_TOOLS=OFF \
    -DGDX_ENABLE_TESTS=OFF \
    -DGDX_ENABLE_TEST_UTILS=OFF \
    -DPython3_EXECUTABLE="$PYTHON" \
    -DPython3_FIND_VIRTUALENV=ONLY \
    -S ${SRC_DIR} \
    -B .

cmake --build . --target install 
