name: CI-windows

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Bootstrap the ports
      run: python bootstrap.py --triplet x64-windows-static-vs2019 --clean-after-build
    - name: Build the code
      run: python build.py --triplet x64-windows-static-vs2019 --run-tests
