name: CI-linux

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Install nasm
      run: sudo apt-get install nasm openssl
    - name: Bootstrap the ports
      run: python bootstrap.py --triplet x64-linux --clean-after-build
    - name: Build the code
      run: python build.py --triplet x64-linux --run-tests
