name: Anaconda build
on: [push]

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      GIT_HASH: ${{ github.sha }}
      GDX_VERSION: 0.14.4
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "windows-2022"]
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          activate-environment: build
          python-version: "3.12"
      - name: create meta.yaml
        run: python
      - name: Setup conda forge
        run: |
          conda config --add channels conda-forge
          conda config --set channel_priority strict
      - name: Install build requirements
        run: conda install mamba boa jinja2
      - name: Generate package metadata
        run: python ./conda/metagen.py
      - name: Build conda package
        run: conda mambabuild ./conda
