name: Anaconda build
on: [push]

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      GIT_HASH: ${{ github.sha }}
      GDX_VERSION: 0.11.8
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          submodules: true
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          activate-environment: build
          python-version: 3.8
      - name: create meta.yaml
        run: python
      - name: Install build requirement
        run: conda install conda-build jinja2
      - name: Generate package metadata
        run: python ./conda/metagen.py
      - name: Build conda package
        run: conda build ./conda

  deploy:
    runs-on: ${{ matrix.os }}
    needs: build
    env:
      REPO_URL: https://repo.vito.be/artifactory/rma-tools-conda-local
      REPO_API_URL: https://repo.vito.be/artifactory/api/conda/rma-tools-conda-local
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Deploy conda package
        run: curl --fail -u${USERNAME}:${PASSWORD} -T $BUILD_FILE -H "X-Checksum-Sha1:$CHECKSUM" "$REPO_URL/$TARGET_FILE"
      - name: trigger index rebuild
        run: curl --fail -u${USERNAME}:${PASSWORD} -X POST "$REPO_API_URL/reindex"
